name: Python quality control pipeline

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  black:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v7
      - name: Install required Python packages
        run: python3.10 -m pip install black --user
      - name: Check formatting with Black
        run: python3.10 -m black --check .
  unit-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v7
      - name: Install required Python packages
        run: python3.10 -m pip install -r requirements_dev.txt --user
      - name: Test with pytest
        run: python3.10 -m pytest
